### ISSUE TITLE
Can increase dotnet2.0 framework for Windown xp and office2007

### ISSUE THREAD

**Issue by MyDelphiRoad** [bovender/VstoAddinInstaller#1]

**Comment by 774115495** [comment]
If the office is running, click cancel to appear the interface for installation, click cancel automatically issue a office again

**Comment by bovender** [comment]
Windows XP has been officially discontinued 3 years ago. If you want to continue using it and need this script to run on XP, please fork it and adjust to your needs. But I would strongly recommend against this. And don't blame me if you become the victim of a malware attack.

Regarding your second comment, can you please rephrase? Is this related to the Windows XP topic?
