### ISSUE TITLE
'/UPDATE' switch doesn't trigger automatic reboot

### ISSUE THREAD

**Issue by ManchesterWuer** [bovender/VstoAddinInstaller#10]
With the help of '/UPDATE' switch, when upgrade, my add-in can automatically close the active Excel and install a new version. However, when the new version's installation wizard is finished, there is no auto-reboot for Excel. I am wondering if there is still another switch for that? Thanks in advance, your tool is very cool.

**Comment by bovender** [comment]
This should be automagically be taken care of by the `DeinitializeSetup` function in [code.pas](../blob/3fa16fc9e719bdea10148259558d3959963c197d/inc/code.pas#L256).

Another option: https://stackoverflow.com/q/3767227/270712

**Comment by ManchesterWuer** [comment]
@bovender Thanks, will try and see.
