### ISSUE TITLE
Unable to compile

### ISSUE THREAD

**Issue by Marmalade118** [bovender/VstoAddinInstaller#2]
Hi,

When trying to compile either a demo or my own project I get a compile error as shown below. Do you have any suggestions?

File:  <path>\VstoAddinInstaller\inc\wizard-pages.pas
Line 43:
Column 10:
Unknown type 'Int64'

Thanks in advance.

![image](https://cloud.githubusercontent.com/assets/11860837/24653432/b169badc-192d-11e7-8fbe-2474892ff2e6.png)

**Comment by bovender** [comment]
That looks like a bitness problem. Can you tell whether you have a 32-bit or 64-bit Windows?

Which version of InnoSetup do you use?

**Comment by Marmalade118** [comment]
Hi,

Thanks for the quick response. I'm using Windows 10 64Bit and version 5.5.9 of the compiler.

**Comment by bovender** [comment]
I believe it's an issue with ANSI vs. Unicode versions of InnoSetup. Is it possible for you to test the current `develop` branch? I've just pushed a fix.

If using the `develop` branch is causing difficulties, you can also edit the file `inc\wizard_pages.pas`:

Replace line 43 (`bytes: Int64;`) with the following five lines:

    #IF DEFINED UNICODE
      bytes: Int64;
    #ELSE
      bytes: DWord;
    #ENDIF

Hope this helps.

**Comment by bovender** [comment]
@lifesnice Did you ever have a chance to run this on your system?
