### ISSUE TITLE
One installer-file for multiple Add-ins

### ISSUE THREAD

**Issue by danielHalan** [bovender/VstoAddinInstaller#5]
Hi, 

Is there any known issues/limitations if one would try to package multiple add-ins (i.e. both Word & Excel) in one Inno-Setup file?

**Comment by bovender** [comment]
I'm afraid that's not supported. It should be feasible though to package several VstoAddinInstaller-generated installers into one installer file which extracts the VstoAddinInstaller files and runs them with command-line switches during installation.

**Comment by bovender** [comment]
Closing as won't fix/workaround provided.
