### ISSUE TITLE
How to use an /UPDATE switch?

### ISSUE THREAD

**Issue by ManchesterWuer** [bovender/VstoAddinInstaller#9]
You mentioned there is an /UPDATE switch to silently shut down and restart the target application after the installation, I guess this is the switch for setting the auto-update function into the add-in. But I feel hard to understand how to use it, can you give me an example of that? Thanks in advance.

**Comment by bovender** [comment]
You add-in needs to implement an automatic update by itself, i.e. checking online for a newer version and downloading it. Once downloaded, you can execute the installer with the `/UPDATE` switch, which basically causes the installer to run silently.

**Comment by ManchesterWuer** [comment]
@bovender Yes, thanks for describing to me the path to make it. But I found it hard to find where is the '/UPDATE' switch. I have searched files like make-installer.iss and some other .iss files in your repository but failed to figure out how to open that switch. Is it a line of code somewhere, for example, added into make-installer.iss?

**Comment by bovender** [comment]
It's defined here: https://github.com/bovender/VstoAddinInstaller/blob/c87f74202f80ed8a676b15a9b8a87d5c8bc6a9aa/inc/code.pas#L63 ;-)

**Comment by ManchesterWuer** [comment]
Thanks, will try and use it.
